version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - registry
      - akeneo
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx-config:/etc/nginx/conf.d
    networks:
      - registry
      - akeneo
    restart: always

networks:
  registry:
    external: true
  akeneo:
    external: true

